# run: conda env create --file environment.yml
name: spbnn
dependencies:
  - python>=3.8
  - pytorch>=2.0.1
  - scikit-learn==1.2.2
  - h5py
  - matplotlib
  - pip:
    - tqdm 
    - medmnist 
    - pydicom  
    
